# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# 1. On importe AUTOMATIQUEMENT tous les contrôleurs qui ont des #[Route]
controllers:
    resource: ../src/Controller/
    type: attribute

# 2. Ta route spécifique pour l'accueil (si elle n'est pas déjà définie en attribut dans HomeController)
home:
    path: /
    controller: App\Controller\HomeController::index